// Code generated by hertz generator.

package main

import (
	"fmt"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/cors"

	"github.com/UnrealMultiple/APMApi/biz/mw"
	"github.com/UnrealMultiple/APMApi/config"
	"github.com/UnrealMultiple/APMApi/pkg/db"
	"github.com/UnrealMultiple/APMApi/pkg/manifest"
)

func init() {
	config.Init()
	db.Init()
	if err := manifest.Load(); err != nil {
		hlog.Warnf("插件清单未加载(等待上传): %v", err)
	}
}

func main() {
	h := server.Default(
		server.WithHostPorts(fmt.Sprintf("%s:%d", config.AppConfig.Server.Host, config.AppConfig.Server.Port)),
		server.WithMaxRequestBodySize(1024*1024*1024), // 1GB
	)

	h.Use(mw.ProcessTime())
	// 允许跨域: 前端部署在 store.terraria.ink, 与API不同源
	h.Use(cors.Default())

	register(h)
	h.Spin()
}
