// Code generated by hertz generator.

package legacy

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getallpluginsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpluginlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpluginzipMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadpluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _get_plugin_manifestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpluginmanifestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _supermarketMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _supermarketxmlMw() []app.HandlerFunc {
	// your code...
	return nil
}
