// Code generated by hertz generator.

package plugin

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadMw() []app.HandlerFunc {
	// your code...
	return nil
}
