// Code generated by hertz generator.

package legacy

import (
	"context"
	"fmt"
	"io"
	"os"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	legacy "github.com/UnrealMultiple/APMApi/biz/model/legacy"
	"github.com/UnrealMultiple/APMApi/biz/pack"
	service "github.com/UnrealMultiple/APMApi/biz/service/legacy"
	"github.com/UnrealMultiple/APMApi/config"
	"github.com/UnrealMultiple/APMApi/pkg/constants"
	"github.com/UnrealMultiple/APMApi/pkg/manifest"
)

// ensureManifest 清单未加载时尝试从磁盘懒加载
func ensureManifest() bool {
	if _, ok := manifest.Raw(); ok {
		return true
	}
	return manifest.Load() == nil
}

// SupermarketXml 镜像信息
// @router /supermarket/xml [GET]
func SupermarketXml(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, &legacy.SupermarketXmlResp{
		Thanks: "此下载镜像由迅猛龙赞助~",
		ICP:    "闽ICP备2024057933号-1",
	})
}

// UploadPlugin 上传插件包
// @router /plugin/upload [POST]
func UploadPlugin(ctx context.Context, c *app.RequestContext) {
	token := c.PostForm("token")
	if token != config.AppConfig.Upload.Key {
		pack.RespLegacyError(c, consts.StatusUnauthorized, "没认证捏~")
		return
	}

	fileHeader, err := c.FormFile("file")
	if err != nil {
		pack.RespLegacyError(c, consts.StatusUnprocessableEntity, "缺少插件包文件")
		return
	}

	file, err := fileHeader.Open()
	if err != nil {
		pack.RespLegacyError(c, consts.StatusInternalServerError, "读取插件包失败")
		return
	}
	defer file.Close()

	content, err := io.ReadAll(file)
	if err != nil {
		pack.RespLegacyError(c, consts.StatusInternalServerError, "读取插件包失败")
		return
	}

	hlog.CtxInfof(ctx, "收到插件包: %s, 大小: %d bytes", fileHeader.Filename, len(content))

	// 与老API行为一致: 处理失败只记录日志, 仍返回成功消息
	if err := service.NewLegacyService(ctx).Upload(content); err != nil {
		hlog.CtxErrorf(ctx, "插件包更新失败: %+v", err)
	} else {
		hlog.CtxInfof(ctx, "插件包更新成功~")
	}

	c.JSON(consts.StatusOK, &legacy.UploadPluginResp{Message: "插件包更新成功~"})
}

// GetPluginList 获取插件清单列表(原样返回 Plugins.json)
// @router /plugin/get_plugin_list [GET]
func GetPluginList(ctx context.Context, c *app.RequestContext) {
	if !ensureManifest() {
		c.String(consts.StatusInternalServerError, "Internal Server Error")
		return
	}
	raw, _ := manifest.Raw()
	c.Data(consts.StatusOK, "application/json", raw)
}

// GetPluginManifest 获取单个插件清单
// @router /plugin/get_plugin_manifest/ [GET]
func GetPluginManifest(ctx context.Context, c *app.RequestContext) {
	if !ensureManifest() {
		c.String(consts.StatusInternalServerError, "Internal Server Error")
		return
	}

	item, ok := manifest.Find(c.Query("assembly_name"))
	if !ok {
		pack.RespLegacyError(c, consts.StatusNotFound, "没有找到这个插件捏~")
		return
	}
	c.Data(consts.StatusOK, "application/json", item)
}

// GetAllPlugins 下载所有插件
// @router /plugin/get_all_plugins [GET]
func GetAllPlugins(ctx context.Context, c *app.RequestContext) {
	if _, err := os.Stat(constants.PluginsZipFile); err != nil {
		pack.RespLegacyError(c, consts.StatusNotFound, "插件包当前未上传,无法下载~")
		return
	}
	if manifest.Syncing() {
		pack.RespLegacyError(c, consts.StatusForbidden, "API正在同步插件中,请稍后重试~")
		return
	}

	if err := pack.RespZipFile(c, constants.PluginsZipFile, "Plugins.zip"); err != nil {
		pack.RespLegacyError(c, consts.StatusInternalServerError, "读取插件包失败")
	}
}

// GetPluginZip 下载单个插件(最新版本)
// @router /plugin/get_plugin_zip [GET]
func GetPluginZip(ctx context.Context, c *app.RequestContext) {
	assemblyName := c.Query("assembly_name")
	svc := service.NewLegacyService(ctx)

	filePath, ok := svc.ResolveLegacyZip(assemblyName)
	if !ok {
		pack.RespLegacyError(c, consts.StatusNotFound, "没有找到指定插件~")
		return
	}
	if manifest.Syncing() {
		pack.RespLegacyError(c, consts.StatusForbidden, "API正在同步插件中,请稍后重试~")
		return
	}

	svc.IncDownloadCount(assemblyName)

	if err := pack.RespZipFile(c, filePath, fmt.Sprintf("%s.zip", assemblyName)); err != nil {
		pack.RespLegacyError(c, consts.StatusInternalServerError, "读取插件失败")
	}
}
