// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	legacy "github.com/UnrealMultiple/APMApi/biz/router/legacy"
	plugin "github.com/UnrealMultiple/APMApi/biz/router/plugin"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	legacy.Register(r)

	plugin.Register(r)
}
