// Code generated by hertz generator.

package plugin

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	plugin "github.com/UnrealMultiple/APMApi/biz/model/plugin"
	"github.com/UnrealMultiple/APMApi/biz/pack"
	service "github.com/UnrealMultiple/APMApi/biz/service/plugin"
	"github.com/UnrealMultiple/APMApi/pkg/errno"
)

// Search 搜索插件
// @router /api/v1/plugin/search [GET]
func Search(ctx context.Context, c *app.RequestContext) {
	var req plugin.SearchReq
	if err := c.BindAndValidate(&req); err != nil {
		pack.RespError(ctx, c, errno.ParamErr.WithError(err))
		return
	}

	data, err := service.NewPluginService(ctx).Search(&req)
	if err != nil {
		pack.RespError(ctx, c, err)
		return
	}

	c.JSON(consts.StatusOK, &plugin.SearchResp{
		Code: errno.SuccessCode,
		Msg:  errno.SuccessMsg,
		Data: data,
	})
}

// List 获取插件列表
// @router /api/v1/plugin/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req plugin.ListReq
	if err := c.BindAndValidate(&req); err != nil {
		pack.RespError(ctx, c, errno.ParamErr.WithError(err))
		return
	}

	data, err := service.NewPluginService(ctx).List(&req)
	if err != nil {
		pack.RespError(ctx, c, err)
		return
	}

	c.JSON(consts.StatusOK, &plugin.ListResp{
		Code: errno.SuccessCode,
		Msg:  errno.SuccessMsg,
		Data: data,
	})
}

// Detail 获取插件详情
// @router /api/v1/plugin/:id/detail [GET]
func Detail(ctx context.Context, c *app.RequestContext) {
	var req plugin.DetailReq
	if err := c.BindAndValidate(&req); err != nil {
		pack.RespError(ctx, c, errno.ParamErr.WithError(err))
		return
	}

	data, err := service.NewPluginService(ctx).Detail(&req)
	if err != nil {
		pack.RespError(ctx, c, err)
		return
	}

	c.JSON(consts.StatusOK, &plugin.DetailResp{
		Code: errno.SuccessCode,
		Msg:  errno.SuccessMsg,
		Data: data,
	})
}

// Rate 评分插件
// @router /api/v1/plugin/rate [POST]
func Rate(ctx context.Context, c *app.RequestContext) {
	var req plugin.RateReq
	if err := c.BindAndValidate(&req); err != nil {
		pack.RespError(ctx, c, errno.ParamErr.WithError(err))
		return
	}

	data, err := service.NewPluginService(ctx).Rate(&req, c.ClientIP())
	if err != nil {
		pack.RespError(ctx, c, err)
		return
	}

	c.JSON(consts.StatusOK, &plugin.RateResp{
		Code: errno.SuccessCode,
		Msg:  errno.SuccessMsg,
		Data: data,
	})
}

// Download 下载插件(默认最新版本, 可用 version 参数指定版本)
// @router /api/v1/plugin/:id/download [GET]
func Download(ctx context.Context, c *app.RequestContext) {
	var req plugin.DownloadReq
	if err := c.BindAndValidate(&req); err != nil {
		pack.RespError(ctx, c, errno.ParamErr.WithError(err))
		return
	}

	filePath, fileName, err := service.NewPluginService(ctx).Download(&req)
	if err != nil {
		pack.RespError(ctx, c, err)
		return
	}

	if err := pack.RespZipFile(c, filePath, fileName); err != nil {
		pack.RespError(ctx, c, err)
	}
}

// DownloadAll 下载所有插件(不增加下载量)
// @router /api/v1/plugin/download_all [GET]
func DownloadAll(ctx context.Context, c *app.RequestContext) {
	filePath, err := service.NewPluginService(ctx).DownloadAll()
	if err != nil {
		pack.RespError(ctx, c, err)
		return
	}

	if err := pack.RespZipFile(c, filePath, "Plugins.zip"); err != nil {
		pack.RespError(ctx, c, err)
	}
}
